In [4]:
# 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

import numpy as np
dizi = np.array([1,2,3,4,5,6], dtype=int)

#Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

print("Oluşturulan dizi: " ,dizi)

print(f"Boyut Sayısı: {dizi.ndim}")

print(f"Eleman Sayısı: {dizi.size}")

Oluşturulan dizi:  [1 2 3 4 5 6]
Boyut Sayısı: 1
Eleman Sayısı: 6


In [9]:
#2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

#İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]
#Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]

dizi1 = np.array([[1,2,6,7],[4,3,9,5]])
dizi2= np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])

print("İlk Oluşturulan dizi: " ,dizi1)

print(f"Boyut Sayısı: {dizi1.ndim}")

print(f"Eleman Sayısı: {dizi1.size}")

print("İkinci Oluşturulan dizi: " ,dizi2)

print(f"Boyut Sayısı: {dizi2.ndim}")

print(f"Eleman Sayısı: {dizi2.size}")

İlk Oluşturulan dizi:  [[1 2 6 7]
 [4 3 9 5]]
Boyut Sayısı: 2
Eleman Sayısı: 8
İkinci Oluşturulan dizi:  [[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut Sayısı: 3
Eleman Sayısı: 12


In [17]:
#3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

#İki boyutlu arraydaki 2 elemanına ulaşalım.

eleman1 = dizi1[0,1]
print(f"Dizideki 1.satır 2.sütun elemanı: {eleman1} ")

#İki boyutlu arraydaki 7 elemanına ulaşalım.

eleman2 = dizi1[0,3]
print(f"Dizideki 1.satır 4.sütun elemanı: {eleman2} ")

#Üç boyutlu arraydaki 9 elemanına ulaşalım.

eleman3 = dizi2[1,1,2]
print(f"Dizideki 2.katman 2.satır 3.sütun elemanı: {eleman3} ")

#Üç boyutlu arraydaki 5 elemanına ulaşalım.

eleman4 = dizi2[0,0,1]
print(f"Dizideki 1.katman 1.satır 2.sütun elemanı: {eleman4} ")

Dizideki 1.satır 2.sütun elemanı: 2 
Dizideki 1.satır 4.sütun elemanı: 7 
Dizideki 2.katman 2.satır 3.sütun elemanı: 9 
Dizideki 1.katman 1.satır 2.sütun elemanı: 5 


In [25]:
#4. Arrayler üzerinde slicing işlemi uygulayalım.

#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

sonuc1 = dizi1[0, 1:3]
print(f"dizi1: {sonuc1}")

#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

sonuc2 = dizi1[1, 1:4]
print(f"dizi1: {sonuc2}")

#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

sonuc3 = dizi2[0, 1, :]
print(f"dizi2: {sonuc3}")

#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

sonuc4 = dizi2[1, 0, 1:3]
print(f"dizi2:{sonuc4}")

dizi1: [2 6]
dizi1: [3 9 5]
dizi2: [21  8 11]
dizi2:[ 6 20]


In [35]:
# 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. 
#Bu arrayleri satır ve sütun bazında birleştirelim.

array1 = np.zeros((5,3),dtype=int)
print("Array 1:", array1)

Array 1: [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [36]:
array2 = np.ones((5,3),dtype=int)
print("Array2:" ,array2)

Array2: [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [37]:
toplam = array1 + array2

print("0 ve 1 matrisinin birleşmiş hali:" ,toplam)

0 ve 1 matrisinin birleşmiş hali: [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
